FROM python:3.12-slim

ENV PIP_NO_CACHE_DIR=1 \
    HF_HUB_ENABLE_HF_TRANSFER=1

RUN pip install --no-cache-dir "huggingface_hub[cli,hf_xet]==0.34.4" hf_transfer==0.1.9

WORKDIR /work
ENTRYPOINT ["hf", "download"]
